name: Bug report
description: Create a report to help us improve
labels: [bug]
title: "[Bug] Short description."
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting issues of WSAOnWin10!

        To make it easier for us to help you please enter detailed information below.
  - type: textarea
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs/Screenshots
      placeholder: If applicable, add logs or screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    attributes:
      label: System (please complete the following information)
      value: |
        Version: [e.g. 22H2]
        Build: [e.g. 19045.3208]
        WSA Version: [e.g. 2305.40000.6.0]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false