name: Custom Build
description: Request a custom WSA build
title: "Custom Build"
labels: ["CustomBuild"]
body:
  - type: dropdown
    id: arch
    attributes:
      label: Target CPU architecture of WSA
      options:
        - x64
        - arm64
    validations:
      required: true
  - type: dropdown
    id: release_type
    attributes:
      label: WSA Release Channel
      options:
        - Retail
        - Release Preview
        - Insider Slow
        - Insider Fast
    validations:
      required: true
  - type: dropdown
    id: root_sol
    attributes:
      label: Root solution
      options:
        - Non-root
        - Magisk Stable
        - Magisk Beta
        - Magisk Canary
        - Magisk Debug
        - KernelSU
    validations:
      required: true
  - type: dropdown
    id: gapps_brand
    attributes:
      label: GApps brand
      options:
        - MindTheGapps
        - OpenGApps
        - No GApps
    validations:
      required: true
  - type: markdown
    id: remove_amazon
    attributes:
      value: "- [x] Remove Amazon"