name: Custom Build
description: Run Actions
title: "Custom Build"
labels: ["CustomBuild"]
body:
  - type: markdown
    attributes:
      value: |
        ## Your custom build will be upload in 15 minutes
  - type: dropdown
    id: arch
    attributes:
      label: Arch
      options:
        - x64
        - arm64
    validations:
      required: true
  - type: dropdown
    id: release_type
    attributes:
      label: WSA Release Channel
      options:
        - Retail
        - Release Preview
        - Insider Slow
        - Insider Fast
    validations:
      required: true
  - type: dropdown
    id: root_sol
    attributes:
      label: Root solution
      options:
        - Non-root
        - KernelSU
        - Magisk
    validations:
      required: true
  - type: dropdown
    id: magisk_ver
    attributes:
      label: Magisk Version
      options:
        - stable
        - beta
        - canary
        - debug
        - release
    validations:
      required: true
  - type: dropdown
    id: gapps_brand
    attributes:
      label: GApps brand
      options:
        - MindTheGapps
        - OpenGApps
        - Non-GApps
    validations:
      required: true
  - type: checkboxes
    id: remove_amazon
    attributes:
      label: Remove Amazon
      options:
        - label: Remove Amazon
