name: Download Original Dll files

on:
  workflow_dispatch:
    inputs:
      arch:
        description: 'Arch'
        required: true
        type: choice
        options:
          - x64
          - arm64
      version:
        description: 'Version(e.g. 22H2)'
        required: false
        type: string
      build:
        description: 'Build(e.g. 22621)'
        required: true
        type: string
      url:
        description: 'Download URL'
        required: true
        type: string
      format:
        description: 'File Format'
        required: true
        type: choice
        options:
          - .iso
          - .zip
          - .vhdx
        default: iso
      upload:
        description: 'Upload'
        required: true
        type: boolean
        default: false

env:
  ARCH: inputs.arch
  VERSION: inputs.version
  BUILD: inputs.build
  URL: inputs.url
  FORMAT: inputs.format
  UPLOAD: inputs.upload
  python-version: '3.10'

jobs:
  download:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Download
        run: |
          python scripts/DownloadDll.py $ARCH $VERSION $BUILD $URL $FORMAT

      - name: commit
        if: env.UPLOAD == true
        run: |
          git config --global user.email 1169942595@qq.com
          git config --global user.name A-JiuA
          git add original_dll/$ARCH/$BUILD
          git commit -m "Upload original dlls from $VERSION $ARCH (build $BUILD)"
          
      - name: Push changes
        if: env.UPLOAD == true
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
