name: Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build WSA
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ['x64', 'arm64']
        root-sol: ['none', 'magisk']
        gapps-brand: ['none', 'MindTheGapps']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone Repository
        run: git clone https://github.com/LSPosed/MagiskOnWSALocal.git

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          check-latest: true
          python-version: '3.x'
          cache: 'pip'
        
      - name: Install Dependencies
        run: |
          pip3 install -r MagiskOnWSALocal/scripts/requirements.txt
          sudo apt update
          sudo apt install -y 7zip lzip patchelf e2fsprogs python3 aria2 attr unzip whiptail qemu-utils p7zip-full python3-venv wine winetricks

      - name: Build WSA ${{ matrix.arch }} With ${{ matrix.root-sol }} ROOT and ${{ matrix.gapps-brand }} GAPPS
        run: |
          ./MagiskOnWSALocal/scripts/build.sh --release-type WIF --remove-amazon --arch ${{ matrix.arch }} --root-sol ${{ matrix.root-sol }} --gapps-brand ${{ matrix.gapps-brand }}
          cp DLLs/${{ matrix.arch }}/*.dll MagiskOnWSALocal/output/*/WsaClient/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: WSA_${{ matrix.arch }}_${{ matrix.root-sol }}_${{ matrix.gapps-brand }} 
          path: MagiskOnWSALocal/output

  make-pri:
    name: Merge language resource
    runs-on: windows-latest
    needs: build
    strategy:
      matrix:
        arch: ['x64', 'arm64']
        root-sol: ['none', 'magisk']
        gapps-brand: ['none', 'MindTheGapps']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          path: ./output/
          name: WSA_${{ matrix.arch }}_${{ matrix.root-sol }}_${{ matrix.gapps-brand }} 

      - name: Copy makepri from WindowsSDK
        run: |
          $dst = Get-ChildItem output -Filter * | Select-Object -First 1 -Expand Name
          cp -Force "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\makepri.exe" "./output/$dst"
        
      - name: Merge language resource
        shell: pwsh
        run: |
          cd ./output/$dst
          $ProcMakePri = Start-Process pwsh.exe -PassThru -NoNewWindow -Args "-ExecutionPolicy Bypass -File MakePri.ps1"
          $ProcMakePri.WaitForExit()
          
      - name: Output
        id: output
        run: echo "foldername=$dst" >> $GITHUB_OUTPUT

      - name: Remove unused artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: WSA_${{ matrix.arch }}_${{ matrix.root-sol }}_${{ matrix.gapps-brand }}
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.output.outputs.foldername }}
          path: output

  upload:
    needs: make-pri
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Get Artifacts Name
        id: result
        uses: MichaelMelena/list-artifacts@v1.01

      - name: Get Artifact Name
        id: name
        env: 
          ARTIFACTS_LIST: ${{ steps.result.outputs.artifacts }}
        run: python3 scripts/get_artifact_name.py

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          path: ./output/
          name: ${{ steps.name.outputs.foldername0 }}
      
      - name: test
        run: |
          echo ${{ steps.result.outputs.artifacts }}
          ls output
  